### ISSUE TITLE
Subnautica multiplayer not starting

### ISSUE THREAD

**Issue by The-sitting-duck** [Papela/Nitrox-Cracked-Mod#18]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### What version of Subnautica are you using?

Feb 2024 72550

### Describe the issue.

I try to start the server but it gave a issue i could't understand

### Describe the steps you took to encounter the bug.

Open Nitrox as admin
Select Subnautica folder
made new server
click to start server
Error

### Relevant log output

![Uploading Screenshot 2024-10-11 162450.png…]()

**Comment by The-sitting-duck** [comment]
Log output

[16:23:55.668] Starting NitroxServer Alpha v1.8.0.2 for Subnautica
[16:23:55.789] Using game files from: C:\Users\User\OneDrive\Documents\Notes\Notes backup\Scary fish game\Subnautica-SteamRIP.com\Subnautica
[16:23:58.311] One or more errors occurred.
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\OneDrive\Documents\Notes\Notes backup\Scary fish game\Subnautica-SteamRIP.com\Subnautica\Subnautica_Data\StreamingAssets\aa\StandaloneWindows64\precursor_prison_aquarium_teleporterterminal_tomoonpool.prefab_5a3ef32b854b9db774c194f993f78e6b.bundle'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NitroxServer_Subnautica.Resources.Parsers.PrefabPlaceholderGroupsParser.<>c__DisplayClass12_0.<GetAllPrefabPlaceholdersGroupsFast>b__0(KeyValuePair`2 keyValuePair) in NitroxServer-Subnautica\Resources\Parsers\PrefabPlaceholderGroupsParser.cs:line 157
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NitroxServer_Subnautica.Resources.Parsers.PrefabPlaceholderGroupsParser.GetAllPrefabPlaceholdersGroupsFast() in NitroxServer-Subnautica\Resources\Parsers\PrefabPlaceholderGroupsParser.cs:line 169
   at NitroxServer_Subnautica.Resources.Parsers.PrefabPlaceholderGroupsParser.ParseFile() in NitroxServer-Subnautica\Resources\Parsers\PrefabPlaceholderGroupsParser.cs:line 55
   at NitroxServer_Subnautica.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Resources\ResourceAssetsParser.cs:line 20
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 47
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 22
   at NitroxServer_Subnautica.Program.<StartServer>d__5.MoveNext() in NitroxServer-Subnautica\Program.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\OneDrive\Documents\Notes\Notes backup\Scary fish game\Subnautica-SteamRIP.com\Subnautica\Subnautica_Data\StreamingAssets\aa\StandaloneWindows64\precursor_prison_aquarium_teleporterterminal_tomoonpool.prefab_5a3ef32b854b9db774c194f993f78e6b.bundle'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NitroxServer_Subnautica.Resources.Parsers.PrefabPlaceholderGroupsParser.<>c__DisplayClass12_0.<GetAllPrefabPlaceholdersGroupsFast>b__0(KeyValuePair`2 keyValuePair) in NitroxServer-Subnautica\Resources\Parsers\PrefabPlaceholderGroupsParser.cs:line 157
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by Papela** [comment]
Surely that version is not compatible, I recommend you use the: **mar.-2023 71288**

**Comment by BlownB2K** [comment]
where do i get the version 71288?

**Comment by Papela** [comment]
Write me on discord: @Papela
