### ISSUE TITLE
Subnautica error when launching the game.

### ISSUE THREAD

**Issue by mikecuongg** [Papela/Nitrox-Cracked-Mod#20]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### What version of Subnautica are you using?

v72550 from Atopgames (cracked)

### Describe the issue.

This error shows when I try to launch the game:
`---------------------------
Error while starting in singleplayer mode
---------------------------
System.InvalidOperationException: Sequence contains no matching element

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)

   at NitroxLauncher.Models.Patching.NitroxEntryPatch.Remove() in NitroxLauncher\Models\Patching\NitroxEntryPatch.cs:line 102

   at NitroxLauncher.LauncherLogic.<StartSingleplayerAsync>d__27.MoveNext() in NitroxLauncher\LauncherLogic.cs:line 184

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at NitroxLauncher.Pages.LaunchGamePage.<SinglePlayerButton_Click>d__7.MoveNext() in NitroxLauncher\Pages\LaunchGamePage.xaml.cs:line 37
---------------------------
OK   
---------------------------
`

### Describe the steps you took to encounter the bug.

1. I have no idea how to fix this bug.

### Relevant log output

https://pastebin.com/H0t5W3mJ

**Comment by Papela** [comment]
Have you changed the game path in the nitrox settings? The log shows that the folder "C:XboxGames\Subnautica\Content" is empty.
I recommend you use the game version: **mar-2023 71288** to avoid further errors

**Comment by darthdemono** [comment]
### I have tested this mod and found a workaround, do this:

1. Get Subnautica version 71288 _(I used dixen18)_
2. Put them in **"C:XboxGames\Subnautica\Content"**, _For some reason the mod doesn't work with any other custom location._
3. Just run the executable in administrator mode
4. Play the game in Multiplayer
